int add(int, int);
void times_table(void);
void jack_bauer(void);
int print_last_digit(int);
int _abs(int);
int print_sign(int n);
int _isalpha(int c);
int _putchar(char c);
void print_alphabet();
void print_alphabet_x10();
int _islower(int c);
